### PR TITLE
Add translate plugin

### PR DESCRIPTION
**Pull request by CianLR**
I hate sam
fr
Je déteste sam

Greetings comrade
ru
Привет товарищ

Quiet road milk girl
ga
Ciúin bóthar cailín bainne

### CODE REVIEW

**Comment by izaakf** [comment]
pr 💯

**Comment by iandioch** [comment]
I like how you didn't give a key <3

**Comment by byxor** [comment]
Where's the code to programmatically fetch a new API key? I'm disgusted. :100:

**Comment by sentriz** [comment]
what about config.py, thats where all the keys are now

**Comment by byxor** [comment]
We don't have access to that, it's not in the repo.

**Comment by CianLR** [comment]
Ah, didn't know that was a thing. Will stick it there

**Pull request merged**
