### PR TITLE
Make 'heads or tails' more interesting

### PR DESCRIPTION
**Pull request by byxor**
Changes:
* Rename command from `.ht` to `.coinflip`.
* Replace images of foreign currency with text.
* Generate a nice message.
* Obtain free credits as a secondary author.

### CODE REVIEW

**Comment by izaakf** [comment]
Senan don't merge this he just wants to up his line count

**Comment by izaakf** [comment]
It is perfectly usable excuse you

**Comment by byxor** [comment]
Steely now generates some speech to spice things up and give it the reed aesthetic.

It's untested, sorry, I don't have python3 on the current laptop.

**Comment by byxor** [comment]
Is this a joke about my extreme disliking to abbreviated variables that I voiced yesterday?

**Comment by izaakf** [comment]
Could be

**Comment by byxor** [comment]
`PROB_SUF` is my probability of suffering if the variables get abbreviated. Its value is `1.0`.

**Comment by byxor** [comment]
Thanks sam

**Comment by sentriz** [comment]
https://github.com/sentriz/steely/commit/653bd70dbfc15176478777752f75be3eea7105b2

**Pull request merged**
