### PR TITLE
Fixed bug giving wrong academic time

### PR DESCRIPTION
**Pull request by gruunday**

### CODE REVIEW

**Comment by byxor** [comment]
This is really cool. What's an academic hour though?

**Comment by sentriz** [comment]
is this 2hour - 1

**Comment by byxor** [comment]
Yes. An academic hour is `(2 * hourOfDay) - 15`, but I'm not sure why.

**Comment by sentriz** [comment]
piccy
is this right?
@byxor it's the nth hour in collage so 8am is 1, 9am is 2, etc I think

but this thing returns 3 for 9

**Comment by gruunday** [comment]
You guys are thinking of it wrong. What hour in the url means is if you had a table it is in the 3rd hour slot. It is not meant to reflect a real hour

**Comment by gruunday** [comment]
8am is 1 8:30 is 2 9 is 3 9:30 is 4 etc

**Comment by sentriz** [comment]
o i see nice

**Comment by byxor** [comment]
Those guys are nutters for naming something "hour" which doesn't correspond to the hour of the day.

**Pull request merged**
