### PR TITLE
display btc in gbp

### PR DESCRIPTION
**Pull request by itsdoddsy**
for multiculturalism mhm mhm

### CODE REVIEW

**Comment by itsdoddsy** [comment]
thank you i aim to please

**Comment by byxor** [comment]
Get yourself an editor that converts tabs to spaces before saving.

**Comment by itsdoddsy** [comment]
i was actually doing it all in console and must've accidentally hit tab and not noticed, i don't use tab

**Comment by iandioch** [comment]
Soon: s/0.9/1.5/

**Pull request merged**
