### PR TITLE
Gex2: Gex gud

### PR DESCRIPTION
**Pull request by iandioch**
Adds a bunch of stuff. More features to come xo

Also makes all gex stuff pep8 compliant.

Merge this before I [add more shit](https://gist.github.com/iandioch/238b3b68b5f4570f05d32fb0450e16a6)

### CODE REVIEW

**Comment by devoxel** [comment]
I think flat directory is getting a bit insane, we should probably move over to plugins having folders

**Comment by iandioch** [comment]
I agree. Also I want to refactor a bunch of stuff in Gex anyway (pep8-ify, and make things like user_name_to_id and user_id_to_name public to all plugins), but I feel like it's good to get this out there asap to see the pain points first.

**Comment by byxor** [comment]
Thanks for fixing the formatting bug.

**Comment by sentriz** [comment]
good product

**Pull request merged**
