### PR TITLE
prevent the spammy boy

### PR DESCRIPTION
**Pull request by izaakf**

### CODE REVIEW

**Comment by izaakf** [comment]
>This👏is👏acceptable👏

I think the clap emoji does a pretty good job at delineating between words

**Comment by sentriz** [comment]
what about just checking if " 👏 " is already in the string, and do nothing if it is?

**Comment by sentriz** [comment]
ok how about a
```
 re.sub(r"(\w)\s(\w)", r"\1 👏 \2", message)
```

we get the spaces, and we get the no spam

**Comment by izaakf** [comment]
I think this is very naughty. goodbye

**Comment by izaakf** [comment]
my code to fix .clap

**Comment by byxor** [comment]
I suppose it can't be broken if the code doesn't exist.

**Comment by izaakf** [comment]
It isn't my fault senan is a dumb slut

**Comment by sentriz** [comment]
SorRy SamM

**Pull request closed without merging**
