### PR TITLE
Hello Sam?

### PR DESCRIPTION
**Pull request by izaakf**
Bringing Reed one step closer to passing the Turing test

### CODE REVIEW

**Comment by sentriz** [comment]
no

**Comment by sentriz** [comment]
ok delete line between author and command, add help string, two lines between help string and author, two lines between command and main()

then mergies

**Comment by sentriz** [comment]
thanks sam

**Comment by sentriz** [comment]
excellent addition to steely

**Comment by izaakf** [comment]
sam please wake up

**Comment by sentriz** [comment]
how to merge on phone?

**Comment by sentriz** [comment]
got it

**Pull request merged**
